name: NPM

on: [push, pull_request]

jobs:
  matrix:
    name: Determine modified packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.modified-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 300
      - name: Commit Range
        id: commit-range
        uses: tue-robotics/tue-env/ci/commit-range@master
      - name: Modified packages
        id: modified-packages
        uses: tue-robotics/tue-env/ci/modified-packages@master
        with:
          commit-range: ${{ steps.commit-range.outputs.commit-range }}
          ignored-packages: launch old
  npm:
    name: NPM - ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.matrix.outputs.packages) }}
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          npm ci --prefix ${{ matrix.package }}
      - name: Build
        run: |
          npm run build --prefix ${{ matrix.package }}
      - name: Success
        run: |
          echo -e "\e[35m\e[1mThe build of '${{ matrix.package }}' has succeeded, please make sure that the 'build'/'dist' folder is up-to-date\e[0m"

